ALTER TABLE "AI_MARKETING_tasks"
ADD COLUMN IF NOT EXISTS worker_id VARCHAR(80);

ALTER TABLE "AI_MARKETING_tasks"
ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "AI_MARKETING_tasks"
ADD COLUMN IF NOT EXISTS started_at TIMESTAMP;

ALTER TABLE "AI_MARKETING_tasks"
ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS "AI_MARKETING_tasks_status_updated_idx"
ON "AI_MARKETING_tasks"(status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS "AI_MARKETING_tasks_lease_idx"
ON "AI_MARKETING_tasks"(lease_expires_at, status);

CREATE TABLE IF NOT EXISTS "AI_MARKETING_rate_limit_buckets" (
  bucket_key VARCHAR(255) PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  reset_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "AI_MARKETING_rate_limit_buckets_reset_idx"
ON "AI_MARKETING_rate_limit_buckets"(reset_at);
